name: gpst_app
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^1.2.0
  cupertino_icons: ^0.1.3
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
  
    - Image/Screen1.jpg
    - Image/Screen2.jpg
    - Image/Screen3.jpg
    - Image/dot-1.jpg
    - Image/dot-2.jpg
    - Image/dot-3.jpg
    - Image/try1.jpg
    - Image/try2.jpg



  fonts:
  
  - family: YatraOne
    fonts:
    - asset: font/YatraOne-Regular.ttf

  - family: Roboto
    fonts:
    - asset:   font/Roboto-Regular.ttf