name: gpst_app
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^1.2.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - Image/5.jpg
  fonts:
  - family: Langar
    fonts:
    - asset: font/Langar-Regular.ttf

  - family: YatraOne
    fonts:
    - asset: font/YatraOne-Regular.ttf